#! /bin/bash
#
# Wrapper for the image server (/usr/local/bin/is)
# used to call the image server as a inetd service
#
read fn xsize ysize zoom contrast xcen ycen wval jpq

/usr/local/bin/is \
    --file-name=$fn \
    --x-size=${xsize:-256} \
    --y-size=${ysize:-256} \
    --zoom=${zoom:-1} \
    --black-pixel=${contrast:-65535} \
    --x-cen=${xcen:-0.5} \
    --y-cen=${ycen:-0.5} \
    --white-pixel=${wval:-0} \
    --jpeg-quality=${jpq:-100} \
    2>/dev/null

